-- Baseline: current schema as generated by Hibernate (ddl-auto=update) prior to Flyway adoption.
-- Uses CREATE TABLE IF NOT EXISTS so Flyway can apply this safely against both empty and existing DBs.
-- On existing DBs, Flyway is configured with baseline-on-migrate=true so this version is typically marked applied without running.

CREATE TABLE IF NOT EXISTS roles (
    id                  VARCHAR(255)                NOT NULL,
    name                VARCHAR(255)                NOT NULL,
    created_by          VARCHAR(255)                NOT NULL,
    created_date        TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    last_modified_by    VARCHAR(255),
    last_modified_date  TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
    id                      VARCHAR(255)                NOT NULL,
    first_name              VARCHAR(255)                NOT NULL,
    last_name               VARCHAR(255)                NOT NULL,
    email                   VARCHAR(255)                NOT NULL,
    phone_number            VARCHAR(255)                NOT NULL,
    password                VARCHAR(255)                NOT NULL,
    date_of_birth           DATE,
    is_enabled              BOOLEAN,
    is_locked               BOOLEAN,
    is_credential_expired   BOOLEAN,
    is_email_verified       BOOLEAN,
    is_phone_verified       BOOLEAN,
    credentials_expired     BOOLEAN,
    created_date            TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    last_modified_date      TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_phone_unique UNIQUE (phone_number)
);

CREATE TABLE IF NOT EXISTS users_roles (
    users_id  VARCHAR(255) NOT NULL,
    roles_id  VARCHAR(255) NOT NULL,
    CONSTRAINT users_roles_users_fk FOREIGN KEY (users_id) REFERENCES users (id),
    CONSTRAINT users_roles_roles_fk FOREIGN KEY (roles_id) REFERENCES roles (id)
);
