springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  security:
    jwt:
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
