import { useEffect, useMemo, useRef, useState } from 'react'
import { Link } from '@tanstack/react-router'
import { Sparkles, FileText, Download } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import {
  useApplication,
  useGenerateApplicationDocuments,
  useUpdateApplication,
} from '@/features/applications/hooks'
import { useDocument, useDocuments, useUpdateDocument } from '@/features/documents/hooks'

interface GeneratorPageProps {
  applicationId: string
}

type SuggestionPriority = 'high' | 'medium' | 'low'

function downloadText(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.click()
  URL.revokeObjectURL(url)
}

function suggestionMeta(text: string, index: number): { type: string; priority: SuggestionPriority } {
  const lower = text.toLowerCase()
  if (lower.includes('remove')) return { type: 'remove', priority: 'low' }
  if (lower.includes('rewrite')) return { type: 'rewrite', priority: 'high' }
  if (lower.includes('add')) return { type: 'add', priority: index % 2 === 0 ? 'high' : 'medium' }
  return { type: 'improve', priority: index % 2 === 0 ? 'medium' : 'low' }
}

function priorityTone(priority: SuggestionPriority) {
  if (priority === 'high') {
    return {
      bg: 'bg-danger-light',
      text: 'text-danger',
    }
  }
  if (priority === 'medium') {
    return {
      bg: 'bg-warning-light',
      text: 'text-warning',
    }
  }

  return {
    bg: 'bg-border',
    text: 'text-muted-foreground',
  }
}

export function GeneratorPage({ applicationId }: Readonly<GeneratorPageProps>) {
  const { data: application, isLoading } = useApplication(applicationId)
  const { data: documents } = useDocuments()

  const generateMutation = useGenerateApplicationDocuments()
  const updateDocumentMutation = useUpdateDocument()
  const updateApplicationMutation = useUpdateApplication()

  const autoGenerated = useRef(false)

  const resumeSummary = useMemo(
    () =>
      documents?.find(
        (document) =>
          document.applicationId === applicationId && document.type === 'TAILORED_RESUME',
      ),
    [applicationId, documents],
  )

  const coverLetterSummary = useMemo(
    () =>
      documents?.find(
        (document) =>
          document.applicationId === applicationId && document.type === 'COVER_LETTER',
      ),
    [applicationId, documents],
  )

  const { data: resumeDocument } = useDocument(resumeSummary?.id ?? '')
  const { data: coverLetterDocument } = useDocument(coverLetterSummary?.id ?? '')

  const [tab, setTab] = useState<'resume' | 'cover'>('resume')
  const [resumeDraft, setResumeDraft] = useState<string | null>(null)
  const [coverLetterDraft, setCoverLetterDraft] = useState<string | null>(null)
  const [manualSuggestions, setManualSuggestions] = useState<string[] | null>(null)
  const [appliedSuggestions, setAppliedSuggestions] = useState<number[]>([])

  useEffect(() => {
    if (application && !resumeSummary && !coverLetterSummary && !autoGenerated.current) {
      autoGenerated.current = true
      generateMutation.mutate(applicationId, {
        onSuccess: (response) => {
          setManualSuggestions(response.suggestions)
          setResumeDraft(response.tailoredResume.content ?? '')
          setCoverLetterDraft(response.coverLetter.content ?? '')
        },
      })
    }
  }, [
    application,
    applicationId,
    coverLetterSummary,
    generateMutation,
    resumeSummary,
  ])

  if (isLoading || !application) {
    return <Skeleton className="h-96 rounded-xl" />
  }

  const resumeContent = resumeDraft ?? resumeDocument?.content ?? ''
  const coverLetterContent = coverLetterDraft ?? coverLetterDocument?.content ?? ''
  const suggestions = manualSuggestions ?? generateMutation.data?.suggestions ?? []
  const generated = Boolean(resumeContent || coverLetterContent)

  return (
    <div className="space-y-5">
      <header className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-[11px] font-bold uppercase tracking-[0.06em] text-muted-foreground">
            CV Generator
          </p>
          <h1 className="mt-1 text-[22px] font-extrabold tracking-[-0.03em] text-foreground">
            {application.jobTitle} · {application.companyName}
          </h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Generate and refine your resume + cover letter for this role.
          </p>
        </div>

        <Link
          to="/tracker"
          className="inline-flex h-8 items-center rounded-md border border-border px-3 text-xs font-semibold text-foreground"
        >
          Back to Tracker
        </Link>
      </header>

      <section className="grid gap-4 xl:grid-cols-[260px_minmax(0,1fr)_minmax(0,1fr)]">
        <aside className="space-y-3">
          <article className="rounded-xl border border-border bg-card p-4">
            <p className="text-[11px] font-bold uppercase tracking-[0.06em] text-muted-foreground">
              Target Job
            </p>
            <div className="mt-3 flex items-start gap-2.5">
              <div className="flex h-8.5 w-8.5 items-center justify-center rounded-[9px] bg-primary-light text-xs font-bold text-primary">
                {application.companyName.slice(0, 2).toUpperCase()}
              </div>
              <div className="min-w-0">
                <p className="truncate text-[13px] font-bold text-foreground">{application.jobTitle}</p>
                <p className="truncate text-[11px] text-muted-foreground">{application.companyName}</p>
              </div>
            </div>
          </article>

          <article className="max-h-[56vh] overflow-y-auto rounded-xl border border-border bg-card p-4">
            <div className="mb-3 flex items-center gap-1.5">
              <Sparkles size={14} className="text-primary" />
              <p className="text-[11px] font-bold uppercase tracking-[0.06em] text-muted-foreground">
                AI Suggestions
              </p>
              <span className="ml-auto rounded-[4px] bg-primary-light px-1.5 py-0.5 text-[10px] font-bold text-primary">
                {Math.max(0, suggestions.length - appliedSuggestions.length)}
              </span>
            </div>

            <div className="space-y-2">
              {suggestions.length === 0 ? (
                <p className="text-xs text-muted-foreground">Generating suggestions...</p>
              ) : (
                suggestions.map((suggestion, index) => {
                  const meta = suggestionMeta(suggestion, index)
                  const tone = priorityTone(meta.priority)
                  const applied = appliedSuggestions.includes(index)

                  return (
                    <article
                      key={`${suggestion}-${index}`}
                      className={`rounded-lg border p-2.5 ${
                        applied
                          ? 'border-success bg-success-light/60 opacity-75'
                          : 'border-border bg-card'
                      }`}
                    >
                      <div className="mb-1.5 flex items-center gap-1.5">
                        <span
                          className={`rounded-[4px] px-1.5 py-0.5 text-[10px] font-bold uppercase ${tone.bg} ${tone.text}`}
                        >
                          {meta.type}
                        </span>
                        <span className={`text-[10px] font-semibold ${tone.text}`}>
                          {meta.priority}
                        </span>
                      </div>
                      <p className="text-xs text-foreground">{suggestion}</p>
                      <button
                        type="button"
                        onClick={() => setAppliedSuggestions((current) => [...new Set([...current, index])])}
                        disabled={applied}
                        className="mt-2 text-[11px] font-semibold text-primary disabled:text-success"
                      >
                        {applied ? 'Applied' : 'Apply suggestion'}
                      </button>
                    </article>
                  )
                })
              )}
            </div>
          </article>

          <Button
            className="h-9 w-full text-[13px] font-bold"
                onClick={() =>
                  generateMutation.mutate(applicationId, {
                    onSuccess: (response) => {
                      setManualSuggestions(response.suggestions)
                      setResumeDraft(response.tailoredResume.content ?? '')
                      setCoverLetterDraft(response.coverLetter.content ?? '')
                      setAppliedSuggestions([])
                    },
                  })
            }
            disabled={generateMutation.isPending}
          >
            {generateMutation.isPending ? 'Generating...' : generated ? 'Regenerate' : 'Generate with AI'}
          </Button>
        </aside>

        <div className="xl:col-span-2">
          <Tabs
            value={tab}
            onValueChange={(value) => setTab(value as 'resume' | 'cover')}
            className="space-y-3"
          >
            <div className="flex items-center justify-between gap-2">
              <TabsList className="h-9 rounded-lg bg-border p-1">
                <TabsTrigger
                  value="resume"
                  className="h-7 rounded-md px-3 text-xs font-semibold data-active:bg-primary data-active:text-primary-foreground"
                >
                  Resume / CV
                </TabsTrigger>
                <TabsTrigger
                  value="cover"
                  className="h-7 rounded-md px-3 text-xs font-semibold data-active:bg-primary data-active:text-primary-foreground"
                >
                  Cover Letter
                </TabsTrigger>
              </TabsList>

              {generated ? (
                <Button
                  variant="outline"
                  className="h-8 gap-1.5 border-success bg-success-light text-xs font-bold text-success"
                  onClick={() =>
                    downloadText(
                      tab === 'resume'
                        ? `${application.companyName}-resume.md`
                        : `${application.companyName}-cover-letter.md`,
                      tab === 'resume' ? resumeContent : coverLetterContent,
                    )
                  }
                >
                  <Download size={12} />
                  Download
                </Button>
              ) : null}
            </div>

            <TabsContent value="resume" className="rounded-xl border border-border bg-card p-4">
              {!generated ? (
                <EmptyPreview label={'Click "Generate with AI" to create your tailored resume'} />
              ) : (
                <>
                  <textarea
                    value={resumeContent}
                    onChange={(event) => setResumeDraft(event.target.value)}
                    className="min-h-[62vh] w-full rounded-lg border border-input bg-background p-4 font-serif text-sm leading-relaxed text-foreground"
                  />
                  <div className="mt-3 flex justify-end gap-2">
                    <Button
                      variant="outline"
                      className="h-8 text-xs"
                      onClick={() =>
                        downloadText(`${application.companyName}-resume.md`, resumeContent)
                      }
                    >
                      Export
                    </Button>
                    <Button
                      className="h-8 text-xs font-bold"
                      onClick={() => {
                        if (resumeSummary) {
                          updateDocumentMutation.mutate({
                            id: resumeSummary.id,
                            data: { content: resumeContent },
                          })
                        }
                      }}
                      disabled={!resumeSummary}
                    >
                      Save Resume Draft
                    </Button>
                  </div>
                </>
              )}
            </TabsContent>

            <TabsContent value="cover" className="rounded-xl border border-border bg-card p-4">
              {!generated ? (
                <EmptyPreview label="Generate to view and edit your cover letter" />
              ) : (
                <>
                  <textarea
                    value={coverLetterContent}
                    onChange={(event) => setCoverLetterDraft(event.target.value)}
                    className="min-h-[62vh] w-full rounded-lg border border-input bg-background p-4 font-serif text-sm leading-[1.8] text-foreground"
                  />
                  <div className="mt-3 flex justify-end gap-2">
                    <Button
                      variant="outline"
                      className="h-8 text-xs"
                      onClick={() =>
                        downloadText(`${application.companyName}-cover-letter.md`, coverLetterContent)
                      }
                    >
                      Export
                    </Button>
                    <Button
                      className="h-8 text-xs font-bold"
                      onClick={() => {
                        if (coverLetterSummary) {
                          updateDocumentMutation.mutate({
                            id: coverLetterSummary.id,
                            data: { content: coverLetterContent },
                          })
                        }
                        updateApplicationMutation.mutate({
                          id: applicationId,
                          data: {
                            coverLetter: coverLetterContent,
                            aiPrepared: true,
                          },
                        })
                      }}
                    >
                      Save Cover Letter
                    </Button>
                  </div>
                </>
              )}
            </TabsContent>
          </Tabs>
        </div>
      </section>
    </div>
  )
}

function EmptyPreview({ label }: { readonly label: string }) {
  return (
    <div className="flex min-h-[62vh] flex-col items-center justify-center rounded-lg border border-dashed border-border bg-background text-center">
      <FileText size={32} className="text-muted-foreground" />
      <p className="mt-3 max-w-sm text-sm text-muted-foreground">{label}</p>
    </div>
  )
}
